# Generated by Django 2.0 on 2019-10-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Mobile_Number', models.IntegerField()),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
